### PR TITLE
Config file stuff

### PR DESCRIPTION
**Pull request by ghost**
This code is pretty mysterious, i think it works because i tested it with 10 diffirent cities and the formatting wasnt weird. but its kind of a mess because i was deleting stuff and forgot to cleanup

### CODE REVIEW

**Review by Heinrich-XIAO — CHANGES_REQUESTED** [review]
Why is this? The only change is from one set of unicodes to the wrong set of unicodes.
image

**Comment by ghost** [comment]
because the previous set of unicodes didnt render well with my fonts

**Comment by ghost** [comment]
and it got annoying to look at

**Comment by Heinrich-XIAO** [comment]
ok, well the new ones don't render well with my font
image
old one on the irhgt and new one on the left

**Comment by ghost** [comment]
This is not as dynamic as what we have now, theoretically we could use the thing with the moon_len and weather_len here but that wouldnt look very nice and take up alot of lines.

**Comment by ghost** [comment]
the only diffirence is that you have some pretty generous maximum values

**Comment by ghost** [comment]
The cool fancy thing didnt work because of that border inbetween the left and right. i think it would be pretty hard to align that correctly 100% of the time

**Comment by s-atrn** [comment]
There you go. That's the reason I wasn't willing to work on this :p well keep on working ig haha

**Comment by ghost** [comment]
Right now it is aligned correctly 100% of the time but i dont like how its done

**Comment by ghost** [comment]
> There you go. That's the reason I wasn't willing to work on this :p well keep on working ig haha

I did it

**Comment by ghost** [comment]
it works

**Comment by ghost** [comment]
if the unicode looks weird on your computer, just change it.

**Comment by ghost** [comment]
with the fancy stuff btw

**Comment by s-atrn** [comment]
Ig we should find some better way to implement the symbols, something that's inclusive to most fonts and terminals

**Comment by ghost** [comment]
a good way would be to find some more common unicode symbols

**Comment by s-atrn** [comment]
Alright. Did a lot of improvements, dw the paddings and borders work good. Also i was having some issue with the yaml. @oblivikun **please provide some default configuration for the yaml file** in the README.md or add it as a file in the repo and in the installation copy it to `.config/richweather/`

**Comment by s-atrn** [comment]
Do the yaml config thing in a new PR, imma merge this one. I'll also add unicodes for most symbols later on.

**Comment by s-atrn** [comment]
Also review my changes before i merge

**Comment by s-atrn** [comment]
@oblivikun i request you to join [my dc server](https://discord.gg/BSCkxtxNJ6) so that we can have better talks

**Comment by ghost** [comment]
I dont use discord, but you can talk on https://tweetor.org

**Comment by s-atrn** [comment]
> Also review my changes before i merge

Everything good? @oblivikun

**Comment by ghost** [comment]
a little formatting stuff

**Comment by ghost** [comment]
should be fine to merge now

**Pull request merged**
