### PR TITLE
make it a real python module

### PR DESCRIPTION
**Pull request by ghost**
This is something with a couple stuff you might want to change in setup.py, you also might want to change the directory structure. but this makes it a real python module that you can upload to pypi later.

### CODE REVIEW

**Comment by s-atrn** [comment]
Thanks for the work you did but i already use data from python-weather which in itself is an API wrapper so i dont think this will be a good idea. So for now im closing the PR, if you have any other suggestions or if you can help me turn into a linux pkg please let me know. You could however fork it and make your own program using my code, i'd encourage it.

**Comment by s-atrn** [comment]
you removed the if __name__ == "__main__" part, how will people now run it as a terminal command?

**Comment by ghost** [comment]
by using the entry point defined in setup.py. you run it by doing pip install . and then just running the built richeweather. You could also do if name name == "main" then call the main function

**Comment by s-atrn** [comment]
Alright then I'll change the author name and in the setup file, add the if name main thing and merge it. Tysm for the contribution!

**Comment by s-atrn** [comment]
Thanks a lot for contributing to richweather! I'm very happy to see your changes working perfectly.

**Pull request merged**
